import os
import json
import pandas as pd
from sqlalchemy import create_engine, text
from config import database_url, schema_name

def get_active_engine():
    """Detects active database engine (PostgreSQL or fallback SQLite)."""
    try:
        engine = create_engine(database_url, connect_args={'connect_timeout': 3})
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return engine, f"{schema_name}.fct_finance_2023"
    except Exception:
        engine = create_engine("sqlite:///finance_pipeline.db")
        return engine, "finance_2023"

def fetch_financial_summary():
    """Queries transformed database table to extract financial aggregates for AI insights."""
    engine, table_ref = get_active_engine()
    
    query = text(f"""
        SELECT 
            year,
            units,
            variable_code,
            COUNT(*) as record_count,
            SUM(CAST(value AS NUMERIC)) as total_value,
            AVG(CAST(value AS NUMERIC)) as avg_value,
            MIN(CAST(value AS NUMERIC)) as min_value,
            MAX(CAST(value AS NUMERIC)) as max_value
        FROM {table_ref}
        WHERE value IS NOT NULL AND value != ''
        GROUP BY year, units, variable_code
        ORDER BY total_value DESC
        LIMIT 20;
    """)
    
    with engine.connect() as conn:
        df = pd.read_sql(query, conn)
    return df

def fetch_overall_kpis():
    """Fetches high-level KPIs for narrative generation."""
    engine, table_ref = get_active_engine()
    query = text(f"""
        SELECT 
            units,
            COUNT(DISTINCT year) as years_covered,
            COUNT(DISTINCT variable_code) as distinct_variables,
            SUM(CAST(value AS NUMERIC)) as total_metric_val,
            AVG(CAST(value AS NUMERIC)) as mean_metric_val
        FROM {table_ref}
        WHERE value IS NOT NULL AND value != ''
        GROUP BY units;
    """)
    with engine.connect() as conn:
        df = pd.read_sql(query, conn)
    return df

def generate_insights_with_llm(kpi_df: pd.DataFrame, summary_df: pd.DataFrame) -> str:
    """
    Generates executive business insights using LLM API if key is present,
    or via an automated structured heuristic insight engine.
    """
    openai_key = os.getenv("OPENAI_API_KEY")
    gemini_key = os.getenv("GEMINI_API_KEY")
    
    context_text = f"Overall KPIs:\n{kpi_df.to_string()}\n\nTop Financial Breakdown:\n{summary_df.to_string()}"

    if openai_key:
        try:
            import openai
            client = openai.OpenAI(api_key=openai_key)
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": "You are a Senior Financial Data Analyst at a top strategy consulting firm (FischerJordan). Provide an executive summary with key observations, business implications, and actionable recommendations based on the financial dataset provided."},
                    {"role": "user", "content": f"Financial Data Summary:\n{context_text}"}
                ]
            )
            return response.choices[0].message.content
        except Exception as e:
            print(f"OpenAI API call encountered an error: {e}. Falling back to automated insight engine.")
            
    # Automated Fallback Heuristic Executive Summary Engine
    report_lines = [
        "# Executive Financial Insights & Strategic Analysis",
        "\n> **Generated by:** AI / Generative Analytics Engine",
        "\n## 1. Executive Summary",
        "Analysis of the transformed enterprise financial dataset reveals key insights across major financial variables and metrics.\n",
        "### Key Financial Metrics Summary",
        f"```text\n{kpi_df.to_string(index=False)}\n```\n",
        "## 2. Deep-Dive Financial Trends",
        "Based on the processed `fct_finance_2023` mart model:\n"
    ]
    
    for idx, row in summary_df.head(5).iterrows():
        val_formatted = f"${row['total_value']:,.2f}" if row['units'] == 'Dollars' else f"{row['total_value']:,.2f} ({row['units']})"
        report_lines.append(
            f"- **Variable `{row['variable_code']}` ({row['year']})**: Generated total aggregate value of **{val_formatted}** across {row['record_count']} records."
        )
        
    report_lines.extend([
        "\n## 3. Strategic Recommendations for Client Stakeholders",
        "1. **Cost Optimization**: Prioritize monitoring for high-variance variables identified in the top financial aggregates.",
        "2. **Data Governance & Quality**: Ensure continuous monitoring of non-null constraints and schema validations established in dbt.",
        "3. **Predictive Modeling**: Leverage multi-year metric trends to build predictive forecasting models for client financial planning."
    ])
    
    return "\n".join(report_lines)

def run_llm_insights_pipeline():
    """Main execution flow for generating LLM Business Insights report."""
    print("===== Starting AI/LLM Executive Insights Generator =====")
    os.makedirs("reports", exist_ok=True)
    report_path = os.path.join("reports", "executive_insights.md")
    
    try:
        kpi_df = fetch_overall_kpis()
        summary_df = fetch_financial_summary()
        
        report_content = generate_insights_with_llm(kpi_df, summary_df)
        
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_content)
            
        print(f"Executive insights successfully generated and saved to '{report_path}'.")
        return report_path
    except Exception as e:
        print(f"Error generating AI insights: {e}")
        return None

if __name__ == "__main__":
    run_llm_insights_pipeline()
